=head1 NAME

Algorithm::NCO - Pure Perl numerically controlled oscillator

=head1 SYNOPSIS

  use Algorithm::NCO;

=head1 AUTHOR

This module was created by Tyler Riddle E<lt>triddle@cpan.orgE<gt>.

=head1 COPYRIGHT

Copyright 2017 Tyler Riddle, all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
